### PR TITLE
[coq] Adapt to coq/coq#9129 "removal of imperative proof state"

### PR DESCRIPTION
**Pull request by ejgallego**

### CODE REVIEW

**Comment by ejgallego** [comment]
Umm, @ppedrot what is going on here? https://gitlab.com/coq/coq/-/jobs/165628596

**Comment by ppedrot** [comment]
This looks very strange...

**Comment by ejgallego** [comment]
> This looks very strange...

The code in that part is fairly tricky, this is where the TC tactics hook in the pretyper?

**Comment by ejgallego** [comment]
Oh so it has nothing to do with that; it seems indeed that ltac2 is not threading the proof state, that is to say, it modifies the proof but discards the result, thus we try to apply `reflexivity` to the initial proof.

**Comment by ejgallego** [comment]
Fixed in new overlay, again a missing warning.

**Comment by maximedenes** [comment]
The Coq PR has been merged, can this get merged too? Thanks!

**Pull request merged**
